### ISSUE TITLE
Org-mode + async leads to: magit-dispatch is not a transient command

### ISSUE THREAD

**Issue by fgiasson** [magit/non-magit-issues#5]
When I use `ob-async` and that I try to run a codeblock using `:async` in `org-mode`, then the SQL query get executed, but once `ob-async` gets the resultsets and tries to update the `#+RESULTS:` section, it dies with the following message:

```
error in process sentinel: async-handle-result: magit-dispatch is not a transient command
error in process sentinel: magit-dispatch is not a transient command
```
I have no idea why it is so.

`(magit-version)` returns:

```
Magit 20190331.1103, Git 2.19.0, Emacs 26.1, darwin
```
`org-version` returns:

```
Org mode version 9.2.2 (9.2.2-21-g03b8d1-elpaplus @ ~/.emacs.d/elpa/develop/org-plus-contrib-20190401/)
```

I just byte recompiled and restarted emacs without any success.

Any idea what may be going on?

**Comment by tarsius** [comment]
Most likely there is no issue in Magit or Transient.

**Comment by tarsius** [comment]
If you cannot figure it out, then beginning the code block with `(require 'magit)` should fix it, even if what it does has nothing to do with Magit.

**Comment by fgiasson** [comment]
@tarsius I guess that should be loaded by `ob-sql` or `ob-async` since the only thing I got in my codeblock is a SQL query. I guess it comes from `ob-async`. The problem is that `magit-dispatch` is not defined/used in any of those projects.

> (I have no idea how ob-async works; does it use the async package?)

looks like it yes.

> If you cannot figure it out, then beginning the code block with (require 'magit) should "fix" it, even if what it does has nothing to do with Magit.

Doesn't seem to work.

it is really weird and only started recently, this was working as expected a few weeks (may a month or two) ago.

**Comment by tarsius** [comment]
>> If you cannot figure it out, then beginning the code block with (require 'magit) should "fix" it, even if what it does has nothing to do with Magit.

> Doesn't seem to work.

Thinking about it again that was actually to be expected. It isn't the code inside the code block that causes `magit` to be needlessly be required but code involved in running the code block. So you have to load `magit` earlier, e.g. in an earlier code block.

> it is really weird and only started recently, this was working as expected a few weeks (may a month or two) ago.

Magit switched from `magit-popup` to `transient`. The former probably just silently ignored a similar messed up situation instead of raising an error.

**Comment by tarsius** [comment]
I'm afraid I don't know what's going on.
